// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (actor_id, actor_name, action, entity_type, entity_id, summary)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_id, actor_name, action, entity_type, entity_id, summary, created_at
`

type CreateAuditLogEntryParams struct {
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorName  string      `json:"actor_name"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Summary    string      `json:"summary"`
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Summary,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorName,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_id, actor_name, action, entity_type, entity_id, summary, created_at FROM audit_log ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListAuditLog(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
