// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultForCurrency = `-- name: ClearDefaultForCurrency :exec
UPDATE bank_accounts SET is_default = false WHERE currency = $1 AND is_default
`

func (q *Queries) ClearDefaultForCurrency(ctx context.Context, currency string) error {
	_, err := q.db.Exec(ctx, clearDefaultForCurrency, currency)
	return err
}

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts (
    bank_name, account_name, account_number, swift_code,
    correspondent_bank, correspondent_account_number, currency, is_default
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, bank_name, account_name, account_number, swift_code, correspondent_bank, correspondent_account_number, currency, is_default, created_at, updated_at
`

type CreateBankAccountParams struct {
	BankName                   string `json:"bank_name"`
	AccountName                string `json:"account_name"`
	AccountNumber              string `json:"account_number"`
	SwiftCode                  string `json:"swift_code"`
	CorrespondentBank          string `json:"correspondent_bank"`
	CorrespondentAccountNumber string `json:"correspondent_account_number"`
	Currency                   string `json:"currency"`
	IsDefault                  bool   `json:"is_default"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.BankName,
		arg.AccountName,
		arg.AccountNumber,
		arg.SwiftCode,
		arg.CorrespondentBank,
		arg.CorrespondentAccountNumber,
		arg.Currency,
		arg.IsDefault,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.SwiftCode,
		&i.CorrespondentBank,
		&i.CorrespondentAccountNumber,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBankAccount = `-- name: DeleteBankAccount :exec
DELETE FROM bank_accounts WHERE id = $1
`

func (q *Queries) DeleteBankAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBankAccount, id)
	return err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT id, bank_name, account_name, account_number, swift_code, correspondent_bank, correspondent_account_number, currency, is_default, created_at, updated_at FROM bank_accounts WHERE id = $1
`

func (q *Queries) GetBankAccount(ctx context.Context, id pgtype.UUID) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccount, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.SwiftCode,
		&i.CorrespondentBank,
		&i.CorrespondentAccountNumber,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultBankAccountForCurrency = `-- name: GetDefaultBankAccountForCurrency :one
SELECT id, bank_name, account_name, account_number, swift_code, correspondent_bank, correspondent_account_number, currency, is_default, created_at, updated_at FROM bank_accounts WHERE currency = $1 ORDER BY is_default DESC, created_at ASC LIMIT 1
`

func (q *Queries) GetDefaultBankAccountForCurrency(ctx context.Context, currency string) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getDefaultBankAccountForCurrency, currency)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.SwiftCode,
		&i.CorrespondentBank,
		&i.CorrespondentAccountNumber,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, bank_name, account_name, account_number, swift_code, correspondent_bank, correspondent_account_number, currency, is_default, created_at, updated_at FROM bank_accounts ORDER BY currency ASC, is_default DESC, bank_name ASC
`

func (q *Queries) ListBankAccounts(ctx context.Context) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.BankName,
			&i.AccountName,
			&i.AccountNumber,
			&i.SwiftCode,
			&i.CorrespondentBank,
			&i.CorrespondentAccountNumber,
			&i.Currency,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccount = `-- name: UpdateBankAccount :one
UPDATE bank_accounts SET
    bank_name = $2,
    account_name = $3,
    account_number = $4,
    swift_code = $5,
    correspondent_bank = $6,
    correspondent_account_number = $7,
    currency = $8,
    is_default = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, bank_name, account_name, account_number, swift_code, correspondent_bank, correspondent_account_number, currency, is_default, created_at, updated_at
`

type UpdateBankAccountParams struct {
	ID                         pgtype.UUID `json:"id"`
	BankName                   string      `json:"bank_name"`
	AccountName                string      `json:"account_name"`
	AccountNumber              string      `json:"account_number"`
	SwiftCode                  string      `json:"swift_code"`
	CorrespondentBank          string      `json:"correspondent_bank"`
	CorrespondentAccountNumber string      `json:"correspondent_account_number"`
	Currency                   string      `json:"currency"`
	IsDefault                  bool        `json:"is_default"`
}

func (q *Queries) UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, updateBankAccount,
		arg.ID,
		arg.BankName,
		arg.AccountName,
		arg.AccountNumber,
		arg.SwiftCode,
		arg.CorrespondentBank,
		arg.CorrespondentAccountNumber,
		arg.Currency,
		arg.IsDefault,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.SwiftCode,
		&i.CorrespondentBank,
		&i.CorrespondentAccountNumber,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
