// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    name, code, logo_path, billing_address, attention_name,
    contact_email, contact_phone, default_currency
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, code, logo_path, billing_address, attention_name, contact_email, contact_phone, default_currency, created_at, updated_at
`

type CreateClientParams struct {
	Name            string      `json:"name"`
	Code            string      `json:"code"`
	LogoPath        pgtype.Text `json:"logo_path"`
	BillingAddress  string      `json:"billing_address"`
	AttentionName   string      `json:"attention_name"`
	ContactEmail    string      `json:"contact_email"`
	ContactPhone    string      `json:"contact_phone"`
	DefaultCurrency string      `json:"default_currency"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Code,
		arg.LogoPath,
		arg.BillingAddress,
		arg.AttentionName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.DefaultCurrency,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.LogoPath,
		&i.BillingAddress,
		&i.AttentionName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.DefaultCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, code, logo_path, billing_address, attention_name, contact_email, contact_phone, default_currency, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.LogoPath,
		&i.BillingAddress,
		&i.AttentionName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.DefaultCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, code, logo_path, billing_address, attention_name, contact_email, contact_phone, default_currency, created_at, updated_at FROM clients ORDER BY name ASC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.LogoPath,
			&i.BillingAddress,
			&i.AttentionName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.DefaultCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
    name = $2,
    code = $3,
    logo_path = $4,
    billing_address = $5,
    attention_name = $6,
    contact_email = $7,
    contact_phone = $8,
    default_currency = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, code, logo_path, billing_address, attention_name, contact_email, contact_phone, default_currency, created_at, updated_at
`

type UpdateClientParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Code            string      `json:"code"`
	LogoPath        pgtype.Text `json:"logo_path"`
	BillingAddress  string      `json:"billing_address"`
	AttentionName   string      `json:"attention_name"`
	ContactEmail    string      `json:"contact_email"`
	ContactPhone    string      `json:"contact_phone"`
	DefaultCurrency string      `json:"default_currency"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.LogoPath,
		arg.BillingAddress,
		arg.AttentionName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.DefaultCurrency,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.LogoPath,
		&i.BillingAddress,
		&i.AttentionName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.DefaultCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
