// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_addresses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listClientAddresses = `-- name: ListClientAddresses :many
SELECT id, client_id, address, created_at FROM client_addresses WHERE client_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListClientAddresses(ctx context.Context, clientID pgtype.UUID) ([]ClientAddress, error) {
	rows, err := q.db.Query(ctx, listClientAddresses, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientAddress
	for rows.Next() {
		var i ClientAddress
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveClientAddress = `-- name: SaveClientAddress :one
INSERT INTO client_addresses (client_id, address)
VALUES ($1, $2)
ON CONFLICT (client_id, address) DO UPDATE SET address = EXCLUDED.address
RETURNING id, client_id, address, created_at
`

type SaveClientAddressParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Address  string      `json:"address"`
}

func (q *Queries) SaveClientAddress(ctx context.Context, arg SaveClientAddressParams) (ClientAddress, error) {
	row := q.db.QueryRow(ctx, saveClientAddress, arg.ClientID, arg.Address)
	var i ClientAddress
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
