// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_settings.sql

package sqlc

import (
	"context"
)

const getCompanySettings = `-- name: GetCompanySettings :one
SELECT id, name, address_line1, address_line2, phone, email, website, tin, rc_number, logo_path, updated_at FROM company_settings LIMIT 1
`

func (q *Queries) GetCompanySettings(ctx context.Context) (CompanySetting, error) {
	row := q.db.QueryRow(ctx, getCompanySettings)
	var i CompanySetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Tin,
		&i.RcNumber,
		&i.LogoPath,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompanySettings = `-- name: UpdateCompanySettings :one
UPDATE company_settings SET
    name = $1,
    address_line1 = $2,
    address_line2 = $3,
    phone = $4,
    email = $5,
    website = $6,
    tin = $7,
    rc_number = $8,
    logo_path = $9,
    updated_at = now()
RETURNING id, name, address_line1, address_line2, phone, email, website, tin, rc_number, logo_path, updated_at
`

type UpdateCompanySettingsParams struct {
	Name         string `json:"name"`
	AddressLine1 string `json:"address_line1"`
	AddressLine2 string `json:"address_line2"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	Website      string `json:"website"`
	Tin          string `json:"tin"`
	RcNumber     string `json:"rc_number"`
	LogoPath     string `json:"logo_path"`
}

func (q *Queries) UpdateCompanySettings(ctx context.Context, arg UpdateCompanySettingsParams) (CompanySetting, error) {
	row := q.db.QueryRow(ctx, updateCompanySettings,
		arg.Name,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.Tin,
		arg.RcNumber,
		arg.LogoPath,
	)
	var i CompanySetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Tin,
		&i.RcNumber,
		&i.LogoPath,
		&i.UpdatedAt,
	)
	return i, err
}
