// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    invoice_no, type, client_id, created_by, currency, invoice_date, due_date,
    contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate,
    vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, bank_account_id,
    billing_address_override, discount_amount, service_entry_number, pdf_title
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
RETURNING id, invoice_no, type, client_id, created_by, status, currency, invoice_date, due_date, contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate, vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, created_at, updated_at, bank_account_id, billing_address_override, discount_amount, public_token, sealed_at, sealed_by_user_id, service_entry_number, pdf_title
`

type CreateInvoiceParams struct {
	InvoiceNo              string      `json:"invoice_no"`
	Type                   InvoiceType `json:"type"`
	ClientID               pgtype.UUID `json:"client_id"`
	CreatedBy              pgtype.UUID `json:"created_by"`
	Currency               string      `json:"currency"`
	InvoiceDate            string      `json:"invoice_date"`
	DueDate                string      `json:"due_date"`
	ContractNo             string      `json:"contract_no"`
	PoNumber               string      `json:"po_number"`
	VendorCode             string      `json:"vendor_code"`
	InvoicePeriod          string      `json:"invoice_period"`
	Subtotal               float64     `json:"subtotal"`
	VatRate                float64     `json:"vat_rate"`
	VatAmount              float64     `json:"vat_amount"`
	GrandTotal             float64     `json:"grand_total"`
	AmountInWords          string      `json:"amount_in_words"`
	Notes                  string      `json:"notes"`
	PreparedByUserID       pgtype.UUID `json:"prepared_by_user_id"`
	BankAccountID          pgtype.UUID `json:"bank_account_id"`
	BillingAddressOverride string      `json:"billing_address_override"`
	DiscountAmount         float64     `json:"discount_amount"`
	ServiceEntryNumber     string      `json:"service_entry_number"`
	PdfTitle               string      `json:"pdf_title"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.InvoiceNo,
		arg.Type,
		arg.ClientID,
		arg.CreatedBy,
		arg.Currency,
		arg.InvoiceDate,
		arg.DueDate,
		arg.ContractNo,
		arg.PoNumber,
		arg.VendorCode,
		arg.InvoicePeriod,
		arg.Subtotal,
		arg.VatRate,
		arg.VatAmount,
		arg.GrandTotal,
		arg.AmountInWords,
		arg.Notes,
		arg.PreparedByUserID,
		arg.BankAccountID,
		arg.BillingAddressOverride,
		arg.DiscountAmount,
		arg.ServiceEntryNumber,
		arg.PdfTitle,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.ClientID,
		&i.CreatedBy,
		&i.Status,
		&i.Currency,
		&i.InvoiceDate,
		&i.DueDate,
		&i.ContractNo,
		&i.PoNumber,
		&i.VendorCode,
		&i.InvoicePeriod,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.AmountInWords,
		&i.Notes,
		&i.PreparedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankAccountID,
		&i.BillingAddressOverride,
		&i.DiscountAmount,
		&i.PublicToken,
		&i.SealedAt,
		&i.SealedByUserID,
		&i.ServiceEntryNumber,
		&i.PdfTitle,
	)
	return i, err
}

const createInvoiceLineItem = `-- name: CreateInvoiceLineItem :one
INSERT INTO invoice_line_items (
    section_id, item_code, description, quantity, rate, amount, meta, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, section_id, item_code, description, quantity, rate, amount, meta, sort_order
`

type CreateInvoiceLineItemParams struct {
	SectionID   pgtype.UUID     `json:"section_id"`
	ItemCode    string          `json:"item_code"`
	Description string          `json:"description"`
	Quantity    float64         `json:"quantity"`
	Rate        float64         `json:"rate"`
	Amount      float64         `json:"amount"`
	Meta        json.RawMessage `json:"meta"`
	SortOrder   int32           `json:"sort_order"`
}

func (q *Queries) CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceLineItem,
		arg.SectionID,
		arg.ItemCode,
		arg.Description,
		arg.Quantity,
		arg.Rate,
		arg.Amount,
		arg.Meta,
		arg.SortOrder,
	)
	var i InvoiceLineItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.ItemCode,
		&i.Description,
		&i.Quantity,
		&i.Rate,
		&i.Amount,
		&i.Meta,
		&i.SortOrder,
	)
	return i, err
}

const createInvoiceSection = `-- name: CreateInvoiceSection :one
INSERT INTO invoice_sections (invoice_id, title, sort_order)
VALUES ($1, $2, $3)
RETURNING id, invoice_id, title, sort_order
`

type CreateInvoiceSectionParams struct {
	InvoiceID pgtype.UUID `json:"invoice_id"`
	Title     string      `json:"title"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateInvoiceSection(ctx context.Context, arg CreateInvoiceSectionParams) (InvoiceSection, error) {
	row := q.db.QueryRow(ctx, createInvoiceSection, arg.InvoiceID, arg.Title, arg.SortOrder)
	var i InvoiceSection
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Title,
		&i.SortOrder,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, invoice_no, type, client_id, created_by, status, currency, invoice_date, due_date, contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate, vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, created_at, updated_at, bank_account_id, billing_address_override, discount_amount, public_token, sealed_at, sealed_by_user_id, service_entry_number, pdf_title FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.ClientID,
		&i.CreatedBy,
		&i.Status,
		&i.Currency,
		&i.InvoiceDate,
		&i.DueDate,
		&i.ContractNo,
		&i.PoNumber,
		&i.VendorCode,
		&i.InvoicePeriod,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.AmountInWords,
		&i.Notes,
		&i.PreparedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankAccountID,
		&i.BillingAddressOverride,
		&i.DiscountAmount,
		&i.PublicToken,
		&i.SealedAt,
		&i.SealedByUserID,
		&i.ServiceEntryNumber,
		&i.PdfTitle,
	)
	return i, err
}

const getInvoiceByPublicToken = `-- name: GetInvoiceByPublicToken :one
SELECT id, invoice_no, type, client_id, created_by, status, currency, invoice_date, due_date, contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate, vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, created_at, updated_at, bank_account_id, billing_address_override, discount_amount, public_token, sealed_at, sealed_by_user_id, service_entry_number, pdf_title FROM invoices WHERE public_token = $1
`

func (q *Queries) GetInvoiceByPublicToken(ctx context.Context, publicToken pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByPublicToken, publicToken)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.ClientID,
		&i.CreatedBy,
		&i.Status,
		&i.Currency,
		&i.InvoiceDate,
		&i.DueDate,
		&i.ContractNo,
		&i.PoNumber,
		&i.VendorCode,
		&i.InvoicePeriod,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.AmountInWords,
		&i.Notes,
		&i.PreparedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankAccountID,
		&i.BillingAddressOverride,
		&i.DiscountAmount,
		&i.PublicToken,
		&i.SealedAt,
		&i.SealedByUserID,
		&i.ServiceEntryNumber,
		&i.PdfTitle,
	)
	return i, err
}

const listInvoiceSectionsByInvoice = `-- name: ListInvoiceSectionsByInvoice :many
SELECT id, invoice_id, title, sort_order FROM invoice_sections WHERE invoice_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListInvoiceSectionsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceSection, error) {
	rows, err := q.db.Query(ctx, listInvoiceSectionsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceSection
	for rows.Next() {
		var i InvoiceSection
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Title,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesWithClient = `-- name: ListInvoicesWithClient :many
SELECT
    i.id, i.invoice_no, i.type, i.status, i.currency, i.invoice_date,
    i.grand_total, i.created_at,
    c.id AS client_id, c.name AS client_name, c.code AS client_code
FROM invoices i
JOIN clients c ON c.id = i.client_id
ORDER BY i.created_at DESC
`

type ListInvoicesWithClientRow struct {
	ID          pgtype.UUID        `json:"id"`
	InvoiceNo   string             `json:"invoice_no"`
	Type        InvoiceType        `json:"type"`
	Status      InvoiceStatus      `json:"status"`
	Currency    string             `json:"currency"`
	InvoiceDate string             `json:"invoice_date"`
	GrandTotal  float64            `json:"grand_total"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ClientID    pgtype.UUID        `json:"client_id"`
	ClientName  string             `json:"client_name"`
	ClientCode  string             `json:"client_code"`
}

func (q *Queries) ListInvoicesWithClient(ctx context.Context) ([]ListInvoicesWithClientRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesWithClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesWithClientRow
	for rows.Next() {
		var i ListInvoicesWithClientRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNo,
			&i.Type,
			&i.Status,
			&i.Currency,
			&i.InvoiceDate,
			&i.GrandTotal,
			&i.CreatedAt,
			&i.ClientID,
			&i.ClientName,
			&i.ClientCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsBySection = `-- name: ListLineItemsBySection :many
SELECT id, section_id, item_code, description, quantity, rate, amount, meta, sort_order FROM invoice_line_items WHERE section_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListLineItemsBySection(ctx context.Context, sectionID pgtype.UUID) ([]InvoiceLineItem, error) {
	rows, err := q.db.Query(ctx, listLineItemsBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceLineItem
	for rows.Next() {
		var i InvoiceLineItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ItemCode,
			&i.Description,
			&i.Quantity,
			&i.Rate,
			&i.Amount,
			&i.Meta,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceNumber = `-- name: NextInvoiceNumber :one
INSERT INTO number_sequences (scope_key, last_value)
VALUES ($1, 1)
ON CONFLICT (scope_key) DO UPDATE SET last_value = number_sequences.last_value + 1
RETURNING last_value
`

func (q *Queries) NextInvoiceNumber(ctx context.Context, scopeKey string) (int32, error) {
	row := q.db.QueryRow(ctx, nextInvoiceNumber, scopeKey)
	var last_value int32
	err := row.Scan(&last_value)
	return last_value, err
}

const sealInvoice = `-- name: SealInvoice :one
UPDATE invoices SET sealed_at = now(), sealed_by_user_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, invoice_no, type, client_id, created_by, status, currency, invoice_date, due_date, contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate, vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, created_at, updated_at, bank_account_id, billing_address_override, discount_amount, public_token, sealed_at, sealed_by_user_id, service_entry_number, pdf_title
`

type SealInvoiceParams struct {
	ID             pgtype.UUID `json:"id"`
	SealedByUserID pgtype.UUID `json:"sealed_by_user_id"`
}

func (q *Queries) SealInvoice(ctx context.Context, arg SealInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, sealInvoice, arg.ID, arg.SealedByUserID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.ClientID,
		&i.CreatedBy,
		&i.Status,
		&i.Currency,
		&i.InvoiceDate,
		&i.DueDate,
		&i.ContractNo,
		&i.PoNumber,
		&i.VendorCode,
		&i.InvoicePeriod,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.AmountInWords,
		&i.Notes,
		&i.PreparedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankAccountID,
		&i.BillingAddressOverride,
		&i.DiscountAmount,
		&i.PublicToken,
		&i.SealedAt,
		&i.SealedByUserID,
		&i.ServiceEntryNumber,
		&i.PdfTitle,
	)
	return i, err
}

const unsealInvoice = `-- name: UnsealInvoice :one
UPDATE invoices SET sealed_at = NULL, sealed_by_user_id = NULL, updated_at = now()
WHERE id = $1
RETURNING id, invoice_no, type, client_id, created_by, status, currency, invoice_date, due_date, contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate, vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, created_at, updated_at, bank_account_id, billing_address_override, discount_amount, public_token, sealed_at, sealed_by_user_id, service_entry_number, pdf_title
`

func (q *Queries) UnsealInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, unsealInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.ClientID,
		&i.CreatedBy,
		&i.Status,
		&i.Currency,
		&i.InvoiceDate,
		&i.DueDate,
		&i.ContractNo,
		&i.PoNumber,
		&i.VendorCode,
		&i.InvoicePeriod,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.AmountInWords,
		&i.Notes,
		&i.PreparedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankAccountID,
		&i.BillingAddressOverride,
		&i.DiscountAmount,
		&i.PublicToken,
		&i.SealedAt,
		&i.SealedByUserID,
		&i.ServiceEntryNumber,
		&i.PdfTitle,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, invoice_no, type, client_id, created_by, status, currency, invoice_date, due_date, contract_no, po_number, vendor_code, invoice_period, subtotal, vat_rate, vat_amount, grand_total, amount_in_words, notes, prepared_by_user_id, created_at, updated_at, bank_account_id, billing_address_override, discount_amount, public_token, sealed_at, sealed_by_user_id, service_entry_number, pdf_title
`

type UpdateInvoiceStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status InvoiceStatus `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.ClientID,
		&i.CreatedBy,
		&i.Status,
		&i.Currency,
		&i.InvoiceDate,
		&i.DueDate,
		&i.ContractNo,
		&i.PoNumber,
		&i.VendorCode,
		&i.InvoicePeriod,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.AmountInWords,
		&i.Notes,
		&i.PreparedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankAccountID,
		&i.BillingAddressOverride,
		&i.DiscountAmount,
		&i.PublicToken,
		&i.SealedAt,
		&i.SealedByUserID,
		&i.ServiceEntryNumber,
		&i.PdfTitle,
	)
	return i, err
}
