// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InvoiceStatus string

const (
	InvoiceStatusDraft InvoiceStatus = "draft"
	InvoiceStatusSent  InvoiceStatus = "sent"
	InvoiceStatusPaid  InvoiceStatus = "paid"
	InvoiceStatusVoid  InvoiceStatus = "void"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type InvoiceType string

const (
	InvoiceTypeStandard InvoiceType = "standard"
	InvoiceTypeProforma InvoiceType = "proforma"
)

func (e *InvoiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceType(s)
	case string:
		*e = InvoiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceType: %T", src)
	}
	return nil
}

type NullInvoiceType struct {
	InvoiceType InvoiceType `json:"invoice_type"`
	Valid       bool        `json:"valid"` // Valid is true if InvoiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceType) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceType), nil
}

type TransmittalStatus string

const (
	TransmittalStatusDraft        TransmittalStatus = "draft"
	TransmittalStatusDispatched   TransmittalStatus = "dispatched"
	TransmittalStatusAcknowledged TransmittalStatus = "acknowledged"
)

func (e *TransmittalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransmittalStatus(s)
	case string:
		*e = TransmittalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransmittalStatus: %T", src)
	}
	return nil
}

type NullTransmittalStatus struct {
	TransmittalStatus TransmittalStatus `json:"transmittal_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransmittalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransmittalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransmittalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransmittalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransmittalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransmittalStatus), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleGm       UserRole = "gm"
	UserRolePreparer UserRole = "preparer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorName  string             `json:"actor_name"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Summary    string             `json:"summary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BankAccount struct {
	ID                         pgtype.UUID        `json:"id"`
	BankName                   string             `json:"bank_name"`
	AccountName                string             `json:"account_name"`
	AccountNumber              string             `json:"account_number"`
	SwiftCode                  string             `json:"swift_code"`
	CorrespondentBank          string             `json:"correspondent_bank"`
	CorrespondentAccountNumber string             `json:"correspondent_account_number"`
	Currency                   string             `json:"currency"`
	IsDefault                  bool               `json:"is_default"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type Client struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Code            string             `json:"code"`
	LogoPath        pgtype.Text        `json:"logo_path"`
	BillingAddress  string             `json:"billing_address"`
	AttentionName   string             `json:"attention_name"`
	ContactEmail    string             `json:"contact_email"`
	ContactPhone    string             `json:"contact_phone"`
	DefaultCurrency string             `json:"default_currency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID               pgtype.UUID        `json:"id"`
	InvoiceNo        string             `json:"invoice_no"`
	Type             InvoiceType        `json:"type"`
	ClientID         pgtype.UUID        `json:"client_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	Status           InvoiceStatus      `json:"status"`
	Currency         string             `json:"currency"`
	InvoiceDate      string             `json:"invoice_date"`
	DueDate          string             `json:"due_date"`
	ContractNo       string             `json:"contract_no"`
	PoNumber         string             `json:"po_number"`
	VendorCode       string             `json:"vendor_code"`
	InvoicePeriod    string             `json:"invoice_period"`
	Subtotal         float64            `json:"subtotal"`
	VatRate          float64            `json:"vat_rate"`
	VatAmount        float64            `json:"vat_amount"`
	GrandTotal       float64            `json:"grand_total"`
	AmountInWords    string             `json:"amount_in_words"`
	Notes            string             `json:"notes"`
	PreparedByUserID pgtype.UUID        `json:"prepared_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BankAccountID    pgtype.UUID        `json:"bank_account_id"`
}

type InvoiceLineItem struct {
	ID          pgtype.UUID     `json:"id"`
	SectionID   pgtype.UUID     `json:"section_id"`
	ItemCode    string          `json:"item_code"`
	Description string          `json:"description"`
	Quantity    float64         `json:"quantity"`
	Rate        float64         `json:"rate"`
	Amount      float64         `json:"amount"`
	Meta        json.RawMessage `json:"meta"`
	SortOrder   int32           `json:"sort_order"`
}

type InvoiceSection struct {
	ID        pgtype.UUID `json:"id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
	Title     string      `json:"title"`
	SortOrder int32       `json:"sort_order"`
}

type NumberSequence struct {
	ScopeKey  string `json:"scope_key"`
	LastValue int32  `json:"last_value"`
}

type Transmittal struct {
	ID               pgtype.UUID        `json:"id"`
	TransmittalNo    string             `json:"transmittal_no"`
	ClientID         pgtype.UUID        `json:"client_id"`
	RelatedInvoiceID pgtype.UUID        `json:"related_invoice_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	Status           TransmittalStatus  `json:"status"`
	TransmittalDate  string             `json:"transmittal_date"`
	Purpose          string             `json:"purpose"`
	ModeOfDispatch   string             `json:"mode_of_dispatch"`
	DispatchedByName string             `json:"dispatched_by_name"`
	ReceivedByName   string             `json:"received_by_name"`
	Remarks          string             `json:"remarks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TransmittalItem struct {
	ID            pgtype.UUID `json:"id"`
	TransmittalID pgtype.UUID `json:"transmittal_id"`
	Description   string      `json:"description"`
	FormatMedium  string      `json:"format_medium"`
	Quantity      float64     `json:"quantity"`
	Remarks       string      `json:"remarks"`
	SortOrder     int32       `json:"sort_order"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
