// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InvoiceStatus string

const (
	InvoiceStatusDraft InvoiceStatus = "draft"
	InvoiceStatusSent  InvoiceStatus = "sent"
	InvoiceStatusPaid  InvoiceStatus = "paid"
	InvoiceStatusVoid  InvoiceStatus = "void"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type InvoiceType string

const (
	InvoiceTypeStandard InvoiceType = "standard"
	InvoiceTypeProforma InvoiceType = "proforma"
)

func (e *InvoiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceType(s)
	case string:
		*e = InvoiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceType: %T", src)
	}
	return nil
}

type NullInvoiceType struct {
	InvoiceType InvoiceType `json:"invoice_type"`
	Valid       bool        `json:"valid"` // Valid is true if InvoiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceType) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceType), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleGm       UserRole = "gm"
	UserRolePreparer UserRole = "preparer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorName  string             `json:"actor_name"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Summary    string             `json:"summary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BankAccount struct {
	ID                         pgtype.UUID        `json:"id"`
	BankName                   string             `json:"bank_name"`
	AccountName                string             `json:"account_name"`
	AccountNumber              string             `json:"account_number"`
	SwiftCode                  string             `json:"swift_code"`
	CorrespondentBank          string             `json:"correspondent_bank"`
	CorrespondentAccountNumber string             `json:"correspondent_account_number"`
	Currency                   string             `json:"currency"`
	IsDefault                  bool               `json:"is_default"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	BankAddress                string             `json:"bank_address"`
	CorrespondentBankAddress   string             `json:"correspondent_bank_address"`
	CorrespondentSwiftCode     string             `json:"correspondent_swift_code"`
	CorrespondentRoutingNumber string             `json:"correspondent_routing_number"`
	CorrespondentAccountName   string             `json:"correspondent_account_name"`
}

type Client struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Code            string             `json:"code"`
	LogoPath        pgtype.Text        `json:"logo_path"`
	BillingAddress  string             `json:"billing_address"`
	AttentionName   string             `json:"attention_name"`
	ContactEmail    string             `json:"contact_email"`
	ContactPhone    string             `json:"contact_phone"`
	DefaultCurrency string             `json:"default_currency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ClientAddress struct {
	ID        pgtype.UUID        `json:"id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CompanySetting struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	AddressLine1 string             `json:"address_line1"`
	AddressLine2 string             `json:"address_line2"`
	Phone        string             `json:"phone"`
	Email        string             `json:"email"`
	Website      string             `json:"website"`
	Tin          string             `json:"tin"`
	RcNumber     string             `json:"rc_number"`
	LogoPath     string             `json:"logo_path"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID                     pgtype.UUID        `json:"id"`
	InvoiceNo              string             `json:"invoice_no"`
	Type                   InvoiceType        `json:"type"`
	ClientID               pgtype.UUID        `json:"client_id"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	Status                 InvoiceStatus      `json:"status"`
	Currency               string             `json:"currency"`
	InvoiceDate            string             `json:"invoice_date"`
	DueDate                string             `json:"due_date"`
	ContractNo             string             `json:"contract_no"`
	PoNumber               string             `json:"po_number"`
	VendorCode             string             `json:"vendor_code"`
	InvoicePeriod          string             `json:"invoice_period"`
	Subtotal               float64            `json:"subtotal"`
	VatRate                float64            `json:"vat_rate"`
	VatAmount              float64            `json:"vat_amount"`
	GrandTotal             float64            `json:"grand_total"`
	AmountInWords          string             `json:"amount_in_words"`
	Notes                  string             `json:"notes"`
	PreparedByUserID       pgtype.UUID        `json:"prepared_by_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	BankAccountID          pgtype.UUID        `json:"bank_account_id"`
	BillingAddressOverride string             `json:"billing_address_override"`
	DiscountAmount         float64            `json:"discount_amount"`
	PublicToken            pgtype.UUID        `json:"public_token"`
	SealedAt               pgtype.Timestamptz `json:"sealed_at"`
	SealedByUserID         pgtype.UUID        `json:"sealed_by_user_id"`
}

type InvoiceLineItem struct {
	ID          pgtype.UUID     `json:"id"`
	SectionID   pgtype.UUID     `json:"section_id"`
	ItemCode    string          `json:"item_code"`
	Description string          `json:"description"`
	Quantity    float64         `json:"quantity"`
	Rate        float64         `json:"rate"`
	Amount      float64         `json:"amount"`
	Meta        json.RawMessage `json:"meta"`
	SortOrder   int32           `json:"sort_order"`
}

type InvoiceSection struct {
	ID        pgtype.UUID `json:"id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
	Title     string      `json:"title"`
	SortOrder int32       `json:"sort_order"`
}

type NumberSequence struct {
	ScopeKey  string `json:"scope_key"`
	LastValue int32  `json:"last_value"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
