// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearDefaultForCurrency(ctx context.Context, currency string) error
	CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error)
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error)
	CreateInvoiceSection(ctx context.Context, arg CreateInvoiceSectionParams) (InvoiceSection, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBankAccount(ctx context.Context, id pgtype.UUID) error
	DeleteClient(ctx context.Context, id pgtype.UUID) error
	GetBankAccount(ctx context.Context, id pgtype.UUID) (BankAccount, error)
	GetClient(ctx context.Context, id pgtype.UUID) (Client, error)
	GetDefaultBankAccountForCurrency(ctx context.Context, currency string) (BankAccount, error)
	GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAuditLog(ctx context.Context) ([]AuditLog, error)
	ListBankAccounts(ctx context.Context) ([]BankAccount, error)
	ListClientAddresses(ctx context.Context, clientID pgtype.UUID) ([]ClientAddress, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListInvoiceSectionsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceSection, error)
	ListInvoicesWithClient(ctx context.Context) ([]ListInvoicesWithClientRow, error)
	ListLineItemsBySection(ctx context.Context, sectionID pgtype.UUID) ([]InvoiceLineItem, error)
	ListUsers(ctx context.Context) ([]User, error)
	NextInvoiceNumber(ctx context.Context, scopeKey string) (int32, error)
	SaveClientAddress(ctx context.Context, arg SaveClientAddressParams) (ClientAddress, error)
	UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
