// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transmittals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransmittal = `-- name: CreateTransmittal :one
INSERT INTO transmittals (
    transmittal_no, client_id, related_invoice_id, created_by, transmittal_date,
    purpose, mode_of_dispatch, dispatched_by_name, received_by_name, remarks
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, transmittal_no, client_id, related_invoice_id, created_by, status, transmittal_date, purpose, mode_of_dispatch, dispatched_by_name, received_by_name, remarks, created_at, updated_at
`

type CreateTransmittalParams struct {
	TransmittalNo    string      `json:"transmittal_no"`
	ClientID         pgtype.UUID `json:"client_id"`
	RelatedInvoiceID pgtype.UUID `json:"related_invoice_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	TransmittalDate  string      `json:"transmittal_date"`
	Purpose          string      `json:"purpose"`
	ModeOfDispatch   string      `json:"mode_of_dispatch"`
	DispatchedByName string      `json:"dispatched_by_name"`
	ReceivedByName   string      `json:"received_by_name"`
	Remarks          string      `json:"remarks"`
}

func (q *Queries) CreateTransmittal(ctx context.Context, arg CreateTransmittalParams) (Transmittal, error) {
	row := q.db.QueryRow(ctx, createTransmittal,
		arg.TransmittalNo,
		arg.ClientID,
		arg.RelatedInvoiceID,
		arg.CreatedBy,
		arg.TransmittalDate,
		arg.Purpose,
		arg.ModeOfDispatch,
		arg.DispatchedByName,
		arg.ReceivedByName,
		arg.Remarks,
	)
	var i Transmittal
	err := row.Scan(
		&i.ID,
		&i.TransmittalNo,
		&i.ClientID,
		&i.RelatedInvoiceID,
		&i.CreatedBy,
		&i.Status,
		&i.TransmittalDate,
		&i.Purpose,
		&i.ModeOfDispatch,
		&i.DispatchedByName,
		&i.ReceivedByName,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransmittalItem = `-- name: CreateTransmittalItem :one
INSERT INTO transmittal_items (
    transmittal_id, description, format_medium, quantity, remarks, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transmittal_id, description, format_medium, quantity, remarks, sort_order
`

type CreateTransmittalItemParams struct {
	TransmittalID pgtype.UUID `json:"transmittal_id"`
	Description   string      `json:"description"`
	FormatMedium  string      `json:"format_medium"`
	Quantity      float64     `json:"quantity"`
	Remarks       string      `json:"remarks"`
	SortOrder     int32       `json:"sort_order"`
}

func (q *Queries) CreateTransmittalItem(ctx context.Context, arg CreateTransmittalItemParams) (TransmittalItem, error) {
	row := q.db.QueryRow(ctx, createTransmittalItem,
		arg.TransmittalID,
		arg.Description,
		arg.FormatMedium,
		arg.Quantity,
		arg.Remarks,
		arg.SortOrder,
	)
	var i TransmittalItem
	err := row.Scan(
		&i.ID,
		&i.TransmittalID,
		&i.Description,
		&i.FormatMedium,
		&i.Quantity,
		&i.Remarks,
		&i.SortOrder,
	)
	return i, err
}

const getTransmittal = `-- name: GetTransmittal :one
SELECT id, transmittal_no, client_id, related_invoice_id, created_by, status, transmittal_date, purpose, mode_of_dispatch, dispatched_by_name, received_by_name, remarks, created_at, updated_at FROM transmittals WHERE id = $1
`

func (q *Queries) GetTransmittal(ctx context.Context, id pgtype.UUID) (Transmittal, error) {
	row := q.db.QueryRow(ctx, getTransmittal, id)
	var i Transmittal
	err := row.Scan(
		&i.ID,
		&i.TransmittalNo,
		&i.ClientID,
		&i.RelatedInvoiceID,
		&i.CreatedBy,
		&i.Status,
		&i.TransmittalDate,
		&i.Purpose,
		&i.ModeOfDispatch,
		&i.DispatchedByName,
		&i.ReceivedByName,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransmittalItems = `-- name: ListTransmittalItems :many
SELECT id, transmittal_id, description, format_medium, quantity, remarks, sort_order FROM transmittal_items WHERE transmittal_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListTransmittalItems(ctx context.Context, transmittalID pgtype.UUID) ([]TransmittalItem, error) {
	rows, err := q.db.Query(ctx, listTransmittalItems, transmittalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransmittalItem
	for rows.Next() {
		var i TransmittalItem
		if err := rows.Scan(
			&i.ID,
			&i.TransmittalID,
			&i.Description,
			&i.FormatMedium,
			&i.Quantity,
			&i.Remarks,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransmittalsWithClient = `-- name: ListTransmittalsWithClient :many
SELECT
    t.id, t.transmittal_no, t.status, t.transmittal_date, t.created_at,
    t.related_invoice_id,
    c.id AS client_id, c.name AS client_name, c.code AS client_code,
    i.invoice_no AS related_invoice_no
FROM transmittals t
JOIN clients c ON c.id = t.client_id
LEFT JOIN invoices i ON i.id = t.related_invoice_id
ORDER BY t.created_at DESC
`

type ListTransmittalsWithClientRow struct {
	ID               pgtype.UUID        `json:"id"`
	TransmittalNo    string             `json:"transmittal_no"`
	Status           TransmittalStatus  `json:"status"`
	TransmittalDate  string             `json:"transmittal_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RelatedInvoiceID pgtype.UUID        `json:"related_invoice_id"`
	ClientID         pgtype.UUID        `json:"client_id"`
	ClientName       string             `json:"client_name"`
	ClientCode       string             `json:"client_code"`
	RelatedInvoiceNo pgtype.Text        `json:"related_invoice_no"`
}

func (q *Queries) ListTransmittalsWithClient(ctx context.Context) ([]ListTransmittalsWithClientRow, error) {
	rows, err := q.db.Query(ctx, listTransmittalsWithClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransmittalsWithClientRow
	for rows.Next() {
		var i ListTransmittalsWithClientRow
		if err := rows.Scan(
			&i.ID,
			&i.TransmittalNo,
			&i.Status,
			&i.TransmittalDate,
			&i.CreatedAt,
			&i.RelatedInvoiceID,
			&i.ClientID,
			&i.ClientName,
			&i.ClientCode,
			&i.RelatedInvoiceNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransmittalStatus = `-- name: UpdateTransmittalStatus :one
UPDATE transmittals SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, transmittal_no, client_id, related_invoice_id, created_by, status, transmittal_date, purpose, mode_of_dispatch, dispatched_by_name, received_by_name, remarks, created_at, updated_at
`

type UpdateTransmittalStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status TransmittalStatus `json:"status"`
}

func (q *Queries) UpdateTransmittalStatus(ctx context.Context, arg UpdateTransmittalStatusParams) (Transmittal, error) {
	row := q.db.QueryRow(ctx, updateTransmittalStatus, arg.ID, arg.Status)
	var i Transmittal
	err := row.Scan(
		&i.ID,
		&i.TransmittalNo,
		&i.ClientID,
		&i.RelatedInvoiceID,
		&i.CreatedBy,
		&i.Status,
		&i.TransmittalDate,
		&i.Purpose,
		&i.ModeOfDispatch,
		&i.DispatchedByName,
		&i.ReceivedByName,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
