CREATE TYPE user_role AS ENUM ('admin', 'gm', 'preparer');

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role user_role NOT NULL DEFAULT 'preparer',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Bootstrap admin account. The password is a random UUID generated by
-- Postgres itself when this migration runs, NOT a fixed string committed
-- to git — hardcoding a real password here would make it permanently
-- public in git history the instant it's committed (this file used to do
-- exactly that; see git log). The account is unusable until
-- scripts/petrodata.sh sets a real password from ADMIN_PASSWORD in .env
-- right after migrations run, on every deploy.
-- pgcrypto's crypt()/gen_salt('bf') produces standard bcrypt hashes,
-- verifiable in Go with golang.org/x/crypto/bcrypt.
INSERT INTO users (name, email, password_hash, role)
VALUES (
    'Administrator',
    'admin@petrodata.net',
    crypt(gen_random_uuid()::text, gen_salt('bf')),
    'admin'
);
